### ISSUE TITLE
Installed via Manager (and StableSwarm) - Nodes Show up but do not work

### ISSUE THREAD

**Issue by mr360photo** [chrisgoringe/cg-use-everywhere#58]
Hello,
I'm using ComfyUI through StableSwarm. I installed the Anywhere Everywhere nodes via the Manager. I get the new nodes, but when I connect them, their status/name doesn't change, and they remain inactive. I also do not get any new options when right clicking on the empty canvas. I tried all the troubleshooting steps from the Readme file. Nothing fixes it. Now, I am definitely showing some use_everywhere errors on the JavaScript console, and here's the log taken from an empty canvas:

**main.js?vary=0.5.7.0:988 Load page...
site.js?vary=0.5.7.0:156 Session started.
main.js?vary=0.5.7.0:992 First session loaded - prepping page.
scripts/app.js:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
logging.js:315 Error loading extension /extensions/use_everywhere/use_everywhere.js TypeError: Failed to fetch dynamically imported module: http://localhost:7801/ComfyBackendDirect/extensions/use_everywhere/use_everywhere.js
console.<computed> @ logging.js:315
logging.js:315 Error loading extension /extensions/use_everywhere/use_everywhere_classes.js TypeError: Failed to fetch dynamically imported module: http://localhost:7801/ComfyBackendDirect/extensions/use_everywhere/use_everywhere_classes.js
console.<computed> @ logging.js:315
logging.js:315 Error loading extension /extensions/use_everywhere/use_everywhere_autocreate.js TypeError: Failed to fetch dynamically imported module: http://localhost:7801/ComfyBackendDirect/extensions/use_everywhere/use_everywhere_autocreate.js
console.<computed> @ logging.js:315
logging.js:315 Error loading extension /extensions/Davemane42/MultiAreaConditioning.js TypeError: Failed to fetch dynamically imported module: http://localhost:7801/ComfyBackendDirect/extensions/Davemane42/MultiAreaConditioning.js
console.<computed> @ logging.js:315
logging.js:315 Error loading extension /extensions/Davemane42/MultiLatentComposite.js TypeError: Failed to fetch dynamically imported module: http://localhost:7801/ComfyBackendDirect/extensions/Davemane42/MultiLatentComposite.js
console.<computed> @ logging.js:315
logging.js:315 Error loading extension /extensions/use_everywhere/use_everywhere_ui.js TypeError: Failed to fetch dynamically imported module: http://localhost:7801/ComfyBackendDirect/extensions/use_everywhere/use_everywhere_ui.js
console.<computed> @ logging.js:315
scripts/api.js:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
logging.js:315 Error loading extension /extensions/ComfyUI-Custom-Scripts/js/autocompleter.js TypeError: Failed to fetch dynamically imported module: http://localhost:7801/ComfyBackendDirect/extensions/ComfyUI-Custom-Scripts/js/autocompleter.js
console.<computed> @ logging.js:315
scripts/widgets.js:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
scripts/ui.js:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
logging.js:315 [BilboX] Installing bilbox.css...
logging.js:315 [🐍 pysssss] Skipping LinkRenderMode as core extension found
Text2Image:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received**

Any hint on to how to fix these errors is much appreciated, tks!

**Comment by chrisgoringe** [comment]
Looks like the javascript files aren't being deployed (for this or for extensions/Davemane42). I don't know anything about StableSwarm, unfortunately.

**Comment by chrisgoringe** [comment]
Raised a question with the StableSwarm repo https://github.com/Stability-AI/StableSwarmUI/issues/180

**Comment by mr360photo** [comment]
Thanks for your reply!

**Comment by chrisgoringe** [comment]
Should be fixed when I do #64

**Comment by mr360photo** [comment]
I'll have to be in later tonight when I get back home ~ I'll keep you posted, thanks again!

**Comment by mr360photo** [comment]
Sorry, not much time available to check ~ quick test after update of Swarm/Comfy/Nodes shows that it still doesn't work. I hope to have more time in the next few days to give you more details but as of now, got to go.

**Comment by chrisgoringe** [comment]
Just now pushed another update which might be relevant, so make sure you have the latest before testing again

**Comment by mr360photo** [comment]
Hi Chris,

Thanks. I won't have access to my computer for the next 12-15 hours. Will
check as soon as I can and will keep you posted.

Thanks again for working on it. Cheers ~
